# Generated by Django 3.0.3 on 2020-07-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
