# Generated by Django 3.0.3 on 2020-09-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputData', '0002_auto_20200717_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
